cat > .github/workflows/pipeline.yml <<'YAML'
name: quick-check
"on":
  push:
    branches:
      - dev
      - main

jobs:
  hello:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - run: echo "Runner OK ✅"
YAML

